language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin
    - DRUPAL_VERSION='8.2.x'

matrix:
  allow_failures:
    - php: 7.1

# Enable Travis containers.
sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

# To be able to run a webbrowser
# If we need anything more powerful
# than e.g. phantomjs
before_install:
  - phpenv config-rm xdebug.ini
  - composer global require "hirak/prestissimo:^0.3"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - git tag 999.0.0
  # Make sure we don't fail when checking out projects
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get latest Drupal 8 core
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch "$DRUPAL_VERSION" --depth 1 https://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/../drupal
  - composer install
  - composer config repositories.0 vcs $TRAVIS_BUILD_DIR
  - composer config repositories.1 composer https://packages.drupal.org/8
  # Add commerce_base for easier testing.
  - composer config repositories.2 vcs https://github.com/drupalcommerce/commerce_base
  - composer require drupalcommerce/commerce_base:dev-8.x-1.x
  - composer require drupal/swiftmailer:1.x-dev
  - composer require drupal/commerce_behat:999.0.0
  - composer require drush/drush

before_script:
  # Start the built-in php web server (mysql is already started) and
  # suppress web-server access logs output.
  - php -S localhost:8888 >& /dev/null &
  # Install the site
  - ./vendor/bin/drush -v site-install commerce_base --db-url=mysql://root:@localhost/drupal --yes

script:
 - ls vendor/drupal/commerce_behat
 - ./vendor/bin/behat --config vendor/drupal/commerce_behat/behat.yml.dist f junit -f pretty -o std
